server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

  datasource:
    url:
      jdbc:postgresql://localhost:5000/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      # ddl-auto와 schema init 중에 한 가지만 사용해야한다. 서로 충돌 할 수 있다. 그러므로 ddl-auto 옵션을 꺼두자.
      # (참고사항 : ddl-auto 기본값은, embedded db일때는 create-drop 아닐때는 none)
      platform: postgres
      schema-locations:
        - classpath*:init-schema.sql
      mode: always
      data-locations:
        - classpath*:init-data.sql